# Generated by Django 2.2 on 2019-04-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopersonalfija',
            name='telefono',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
