# Generated by Django 2.2 on 2019-04-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0002_infopersonalfija_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopersonalfija',
            name='puesto',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
