# Generated by Django 2.2 on 2019-04-03 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0003_infopersonalfija_puesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienespersonas',
            name='cat_tipo_participacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='declaracion.CatTipoParticipacion'),
            preserve_default=False,
        ),
    ]
