# Generated by Django 2.2 on 2019-04-03 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0003_infopersonalfija_puesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaraciones',
            name='cat_estatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='declaracion.CatEstatusDeclaracion'),
        ),
    ]
