# Generated by Django 2.2 on 2019-04-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0004_declaraciones_cat_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaraciones',
            name='avance',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
