# Generated by Django 2.2 on 2019-04-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0004_auto_20190403_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bienespersonas',
            old_name='bien_activosbienes',
            new_name='activos_bienes',
        ),
        migrations.RenameField(
            model_name='bienespersonas',
            old_name='propietario_infopersonalvar',
            new_name='info_personal_var',
        ),
        migrations.AddField(
            model_name='infopersonalvar',
            name='activos_bienes',
            field=models.ManyToManyField(related_name='info_personal_var_activos_bienes', through='declaracion.BienesPersonas', to='declaracion.ActivosBienes'),
        ),
    ]
