# Generated by Django 2.2 on 2019-04-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0005_auto_20190403_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='fideicomisos',
            name='nombre_fideicomiso',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
