# Generated by Django 2.2 on 2019-04-04 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0007_fideicomisos_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienespersonas',
            name='info_personal_var',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bienes_personas_info_personal_var', to='declaracion.InfoPersonalVar'),
        ),
    ]
