# Generated by Django 2.2 on 2019-04-04 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0008_auto_20190404_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienespersonas',
            name='otra_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bienes_personas_otra_persona', to='declaracion.InfoPersonalVar'),
        ),
    ]
