# Generated by Django 2.2 on 2019-04-04 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0009_auto_20190404_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversiones',
            name='cat_unidades_temporales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='declaracion.CatUnidadesTemporales'),
        ),
    ]
