# Generated by Django 2.2 on 2019-04-04 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0010_auto_20190404_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bienesintangibles',
            name='propietario_registrado',
        ),
    ]
