# Generated by Django 2.2 on 2019-04-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0011_remove_bienesintangibles_propietario_registrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentasporcobrar',
            name='num_registro',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
