# Generated by Django 2.2 on 2019-04-04 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0005_declaraciones_avance'),
        ('declaracion', '0012_cuentasporcobrar_num_registro'),
    ]

    operations = [
    ]
