# Generated by Django 2.2 on 2019-04-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0017_catcamposobligatorios'),
    ]

    operations = [
        migrations.AddField(
            model_name='catcamposobligatorios',
            name='es_principal',
            field=models.BooleanField(default=False),
        ),
    ]
