# Generated by Django 2.2 on 2019-04-07 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0018_catcamposobligatorios_es_principal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catnaturalezamembresia',
            options={'ordering': ['orden']},
        ),
    ]
