# Generated by Django 2.2 on 2019-04-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0019_auto_20190407_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infopersonalvar',
            options={'ordering': ('pk',)},
        ),
        migrations.RemoveField(
            model_name='fideicomisos',
            name='fideicomisario',
        ),
        migrations.AddField(
            model_name='membresias',
            name='tiene_apoyos',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
