# Generated by Django 2.2 on 2019-04-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0021_remove_membresias_tiene_apoyos'),
    ]

    operations = [
        migrations.AddField(
            model_name='conyugedependientes',
            name='tiene_apoyos',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
