# Generated by Django 2.2 on 2019-04-08 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0022_conyugedependientes_tiene_apoyos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inversiones',
            name='cat_tipos_titulares',
        ),
        migrations.AddField(
            model_name='inversiones',
            name='cat_tipos_titulares',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='declaracion.CatTiposTitulares'),
        ),
    ]
