# Generated by Django 2.2 on 2019-04-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0023_auto_20190408_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresias',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
