# Generated by Django 2.2 on 2019-04-12 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0024_membresias_monto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catmonedas',
            options={'ordering': ['moneda']},
        ),
        migrations.AlterField(
            model_name='declaraciones',
            name='cat_estatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='declaracion.CatEstatusDeclaracion'),
        ),
    ]
