# Generated by Django 2.2 on 2019-04-16 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0025_auto_20190412_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoyos',
            name='declaraciones',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='declaracion.Declaraciones'),
            preserve_default=False,
        ),
    ]
