# Generated by Django 2.2 on 2019-04-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0026_apoyos_declaraciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='catcamposobligatorios',
            name='tipo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='secciondeclaracion',
            name='max',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='secciondeclaracion',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
