# Generated by Django 2.2 on 2019-04-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0027_auto_20190418_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='catcamposobligatorios',
            name='esta_pantalla',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='secciondeclaracion',
            name='max',
            field=models.IntegerField(default=1),
        ),
    ]
