# Generated by Django 2.2 on 2019-04-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0028_auto_20190422_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='conyugedependientes',
            name='otra_relacion_familiar',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
