# Generated by Django 2.2 on 2019-04-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0031_auto_20190423_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaraciones',
            name='sello',
            field=models.TextField(blank=True),
        ),
    ]
