# Generated by Django 2.2 on 2019-04-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0032_declaraciones_sello'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaraciones',
            name='fecha_recepcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
